version: "3.8"

services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: null
            MYSQL_DATABASE: test
        ports:
            - "3306:3306"

    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "4000:4000"
        depends_on:
            - mysql
